#!/usr/bin/python

import argparse
import logging
import os

from lets_enc import certificate
from lets_enc import acme
from lets_enc import parser

arg_parser = argparse.ArgumentParser()
arg_parser.add_argument("-p","--path", required=False, help="Path where certificate files are/will be stored")
arg_parser.add_argument("-d","--domain", required=True, help="The domain to be signed")
arg_parser.add_argument("--acme-dir", required=True, help="path to the .well-known/acme-challenge/ directory")
arg_parser.add_argument("-t","--lifetime", type=int, required=False, help="Minimum remaining cert lifetime")

args = arg_parser.parse_args()

def chall(path,data=None):
    path = os.path.join(args.acme_dir,path)
    if data is None:
        os.unlink(path)
    else:
        with open(path,"wb") as f:
            f.write(data)

d={}
if args.path:
    d['path'] = args.path
if args.lifetime:
    d['lifetime'] = args.lifetime
c,k,d = get_cert(args.domain, chall, **d)
print("CERT",c)
print("KEY",k)
print("EXPIRY",d/3600/24)

